[[plugins]]
  package = "netlify-plugin-no-more-404"
    [plugins.inputs]
      on404 = 'error'
      cacheKey = 'anystring'

[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir = "."
  prettyURLs = true
  homepage = "https://arjun.me"
  exclude = [
    '**/**/certifications.html',
    '**/**/achievements.html'
  ]

[[redirects]]
  from = "/achievements"
  to = "/"
  status = 301

[[redirects]]
  from = "/achievements.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/certifications"
  to = "/"
  status = 301

[[redirects]]
  from = "/certifications.html"
  to = "/"
  status = 301